# Generated by Django 5.0.6 on 2024-06-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(db_column='idSERVICIO', primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('foto', models.ImageField(null=True, upload_to='servicios')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
